// Machine translation mistranslates context-free ingredient names (e.g.
// "Lime" → "Chaux", the mineral). These hand-checked French labels override
// MT for common cocktail ingredients. Keys are matched case-insensitively.
export const INGREDIENT_OVERRIDES: Record<string, string> = {
  lime: "Citron vert",
  "lime juice": "Jus de citron vert",
  lemon: "Citron",
  "lemon juice": "Jus de citron",
  "soda water": "Eau gazeuse",
  "club soda": "Eau gazeuse",
  "carbonated water": "Eau gazeuse",
  "sparkling water": "Eau pétillante",
  "tonic water": "Eau tonique",
  "ginger ale": "Soda au gingembre",
  "ginger beer": "Bière de gingembre",
  water: "Eau",
  ice: "Glace",
  sugar: "Sucre",
  "powdered sugar": "Sucre glace",
  "sugar syrup": "Sirop de sucre",
  "simple syrup": "Sirop de sucre",
  salt: "Sel",
  mint: "Menthe",
  honey: "Miel",
  milk: "Lait",
  cream: "Crème",
  "heavy cream": "Crème épaisse",
  "egg white": "Blanc d’œuf",
  "egg yolk": "Jaune d’œuf",
  egg: "Œuf",
  coffee: "Café",
  cinnamon: "Cannelle",
  nutmeg: "Noix de muscade",
  "light rum": "Rhum blanc",
  "white rum": "Rhum blanc",
  "dark rum": "Rhum brun",
  "spiced rum": "Rhum épicé",
  "gold rum": "Rhum ambré",
  rum: "Rhum",
  whiskey: "Whiskey",
  whisky: "Whisky",
  "scotch whisky": "Whisky écossais",
  bourbon: "Bourbon",
  brandy: "Brandy",
  cognac: "Cognac",
  vodka: "Vodka",
  gin: "Gin",
  tequila: "Tequila",
  "dry vermouth": "Vermouth sec",
  "sweet vermouth": "Vermouth doux",
  vermouth: "Vermouth",
  "triple sec": "Triple sec",
  grenadine: "Grenadine",
  "orange juice": "Jus d’orange",
  "pineapple juice": "Jus d’ananas",
  "cranberry juice": "Jus de canneberge",
  "apple juice": "Jus de pomme",
  "tomato juice": "Jus de tomate",
  "grapefruit juice": "Jus de pamplemousse",
  lemonade: "Limonade",
  cola: "Cola",
  "coca-cola": "Coca-Cola",
  sugarsyrup: "Sirop de sucre",
};

/** Returns the override for an English ingredient name, or null. */
export function ingredientOverride(nameEn: string): string | null {
  return INGREDIENT_OVERRIDES[nameEn.trim().toLowerCase()] ?? null;
}
